#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# npx eslint . --cache --ext .ts,.html --fix have to fix the lint error

# Basic check: prevent empty commit messages
if test -z "$(cat "$1")"; then
  echo "❌ Commit message cannot be empty."
  exit 1
fi

